# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: gci env:* | sort-object name
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
        nuget install secure-file -ExcludeVersion
        secure-file\tools\secure-file -decrypt tests/testthat/av_supersecret.enc -secret $env:my_secret -out tests/testthat/supersecret
      }
  - ps: Test-Path tests/testthat/supersecret -PathType Leaf
  - ps: Bootstrap

environment:
  my_secret:
    secure: cCzcfyH7ESZziA53h23oUw==

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - Rscript -e "Sys.getenv()"
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
